export const URL_API = 'http://194.58.70.179/';
export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const AUTH_SET_CURRENTUSER = 'AUTH_SET_CURRENTUSER';
export const AUTH_SET_LOGIN_ERROR = 'AUTH_SET_LOGIN_ERROR';
