export const URL_API = "http://132.226.205.101/";
export const COUNTER_CHANGE = "COUNTER_CHANGE";
export const AUTH_SET_CURRENTUSER = "AUTH_SET_CURRENTUSER";
export const AUTH_SET_LOGIN_ERROR = "AUTH_SET_LOGIN_ERROR";
export const AUTH_SET_REGISTER_ERROR = "AUTH_SET_REGISTER_ERROR";
export const PROFILE_LOAD_DATA = "PROFILE_LOAD_DATA";
export const PROFILE_GET_MY = "PROFILE_GET_MY";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
